# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rnn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rnn.proto',
  package='tensorflow.Source.lm.rnn',
  syntax='proto3',
  serialized_pb=_b('\n\trnn.proto\x12\x18tensorflow.Source.lm.rnn\"\xa2\x02\n\x08RNNProto\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.tensorflow.Source.lm.rnn.Type\x12\x19\n\x11input_tensor_name\x18\x02 \x01(\t\x12\x1f\n\x17predictions_tensor_name\x18\x03 \x01(\t\x12<\n\x01h\x18\x04 \x03(\x0b\x32\x31.tensorflow.Source.lm.rnn.RNNProto.TensorNamePair\x12<\n\x01\x63\x18\x05 \x03(\x0b\x32\x31.tensorflow.Source.lm.rnn.RNNProto.TensorNamePair\x1a\x30\n\x0eTensorNamePair\x12\x0f\n\x07initial\x18\x01 \x01(\t\x12\r\n\x05\x66inal\x18\x02 \x01(\t*&\n\x04Type\x12\x0b\n\x07VANILLA\x10\x00\x12\x07\n\x03GRU\x10\x01\x12\x08\n\x04LSTM\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='tensorflow.Source.lm.rnn.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VANILLA', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRU', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LSTM', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=332,
  serialized_end=370,
)
_sym_db.RegisterEnumDescriptor(_TYPE)

Type = enum_type_wrapper.EnumTypeWrapper(_TYPE)
VANILLA = 0
GRU = 1
LSTM = 2



_RNNPROTO_TENSORNAMEPAIR = _descriptor.Descriptor(
  name='TensorNamePair',
  full_name='tensorflow.Source.lm.rnn.RNNProto.TensorNamePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initial', full_name='tensorflow.Source.lm.rnn.RNNProto.TensorNamePair.initial', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='final', full_name='tensorflow.Source.lm.rnn.RNNProto.TensorNamePair.final', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=330,
)

_RNNPROTO = _descriptor.Descriptor(
  name='RNNProto',
  full_name='tensorflow.Source.lm.rnn.RNNProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='tensorflow.Source.lm.rnn.RNNProto.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_tensor_name', full_name='tensorflow.Source.lm.rnn.RNNProto.input_tensor_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='predictions_tensor_name', full_name='tensorflow.Source.lm.rnn.RNNProto.predictions_tensor_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='h', full_name='tensorflow.Source.lm.rnn.RNNProto.h', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c', full_name='tensorflow.Source.lm.rnn.RNNProto.c', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RNNPROTO_TENSORNAMEPAIR, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=330,
)

_RNNPROTO_TENSORNAMEPAIR.containing_type = _RNNPROTO
_RNNPROTO.fields_by_name['type'].enum_type = _TYPE
_RNNPROTO.fields_by_name['h'].message_type = _RNNPROTO_TENSORNAMEPAIR
_RNNPROTO.fields_by_name['c'].message_type = _RNNPROTO_TENSORNAMEPAIR
DESCRIPTOR.message_types_by_name['RNNProto'] = _RNNPROTO
DESCRIPTOR.enum_types_by_name['Type'] = _TYPE

RNNProto = _reflection.GeneratedProtocolMessageType('RNNProto', (_message.Message,), dict(

  TensorNamePair = _reflection.GeneratedProtocolMessageType('TensorNamePair', (_message.Message,), dict(
    DESCRIPTOR = _RNNPROTO_TENSORNAMEPAIR,
    __module__ = 'rnn_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.Source.lm.rnn.RNNProto.TensorNamePair)
    ))
  ,
  DESCRIPTOR = _RNNPROTO,
  __module__ = 'rnn_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.Source.lm.rnn.RNNProto)
  ))
_sym_db.RegisterMessage(RNNProto)
_sym_db.RegisterMessage(RNNProto.TensorNamePair)


# @@protoc_insertion_point(module_scope)
