# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vocab.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vocab.proto',
  package='tensorflow.Source.lm',
  syntax='proto3',
  serialized_pb=_b('\n\x0bvocab.proto\x12\x14tensorflow.Source.lm\"z\n\nVocabProto\x12\x15\n\rmin_frequency\x18\x01 \x01(\x05\x12\x33\n\x04item\x18\x02 \x03(\x0b\x32%.tensorflow.Source.lm.VocabProto.Item\x1a \n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04word\x18\x02 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VOCABPROTO_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='tensorflow.Source.lm.VocabProto.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tensorflow.Source.lm.VocabProto.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='word', full_name='tensorflow.Source.lm.VocabProto.Item.word', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=159,
)

_VOCABPROTO = _descriptor.Descriptor(
  name='VocabProto',
  full_name='tensorflow.Source.lm.VocabProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_frequency', full_name='tensorflow.Source.lm.VocabProto.min_frequency', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='tensorflow.Source.lm.VocabProto.item', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_VOCABPROTO_ITEM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=159,
)

_VOCABPROTO_ITEM.containing_type = _VOCABPROTO
_VOCABPROTO.fields_by_name['item'].message_type = _VOCABPROTO_ITEM
DESCRIPTOR.message_types_by_name['VocabProto'] = _VOCABPROTO

VocabProto = _reflection.GeneratedProtocolMessageType('VocabProto', (_message.Message,), dict(

  Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
    DESCRIPTOR = _VOCABPROTO_ITEM,
    __module__ = 'vocab_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.Source.lm.VocabProto.Item)
    ))
  ,
  DESCRIPTOR = _VOCABPROTO,
  __module__ = 'vocab_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.Source.lm.VocabProto)
  ))
_sym_db.RegisterMessage(VocabProto)
_sym_db.RegisterMessage(VocabProto.Item)


# @@protoc_insertion_point(module_scope)
